# Generated by Django 4.2 on 2023-06-23 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usr_chat', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
