# Generated by Django 4.2 on 2023-06-24 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr_chat', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='roomid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
