# Generated by Django 4.2 on 2023-06-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr_chat', '0004_message_roomid'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='senderUsername',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
